version: '1.5'
name: 'meo-3-docker-compose'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-mqtt
    hostname: mosquitto-mqtt
    volumes:
      - ./mosquitto-vol:/mosquitto/data
      - ./mosquitto-vol:/mosquitto/log
      - type: bind
        source: ./mosquitto-vol/mosquitto/config/mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
      - "9001:9001"
    expose:
      - "1883"
    networks:
      - meo-3-net

  node-red:
    image: meo-nodered:1.0
    container_name: meo-nodered
    volumes:
      - ./node-red-vol:/node-red/data
    ports:
      - "1880:1880"
    networks:
      - meo-3-net
    links:
      - mosquitto
    depends_on:
      - mosquitto

networks:
  meo-3-net:
    driver: bridge

volumes:
  node-red-vol: # Path: node-red-data
  mosquitto-vol: # Path: mosquitto-data